# Generated by Django 4.2.7 on 2023-11-05 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('requests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('deals', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
            ],
        ),
    ]
