# Generated by Django 4.2.7 on 2023-11-05 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.CharField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_sold', models.CharField()),
                ('coin_purchased', models.CharField()),
                ('amount_sell', models.FloatField(null=True)),
                ('amount_purchase', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('finished', models.BooleanField()),
                ('successful', models.BooleanField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('coin', models.CharField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitraryRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chat')),
            ],
        ),
    ]
