# Generated by Django 4.2.7 on 2023-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='finished_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
