# Generated by Django 4.2.7 on 2023-11-05 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_chat_deals_alter_chat_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='deals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chat',
            name='requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
